version: '3'

services:
  web:
    image: nginx:1.13
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx:/etc/nginx/conf.d/
  fpm:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
#    links:
#      - db:postgres
#    depends_on:
#      - db
#  composer:
#    restart: 'no'
#    image: composer/composer:php7
#    command: install
#    volumes:
#      - .:/app
  db:
    image: postgres:9.6
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "12345678"

